trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: Default

parameters:
  - name: env
    displayName: "Ambiente de ejecución"
    type: string
    default: "qa"
    values:
      - qa
      - devel
      - pre-prod

variables:
  ENV: ${{ parameters.env }}

stages:
  - stage: Test
    displayName: Ejecutar pruebas Karate en Windows
    jobs:
      - job: karateTests
        displayName: Run Karate Tests
        steps:

          - task: DownloadSecureFile@1
            name: tnsora
            inputs:
              secureFile: "tnsnames.ora"
            displayName: Descargar archivo tnsnames.ora

          - powershell: |
              Write-Host "📁 Configurando TNS_ADMIN..."
              $tnsPath = "$(Build.SourcesDirectory)\.oracle\network\admin"
              New-Item -Path $tnsPath -ItemType Directory -Force | Out-Null
              Copy-Item -Path "$(tnsora.secureFilePath)" -Destination "$tnsPath\tnsnames.ora" -Force
            displayName: Configurar TNS_ADMIN en Windows

          - powershell: |
              Write-Host "🔐 Desencriptando archivos de entorno..."
              $env:ENV_SECRET_KEY = "$(ENV_SECRET_KEY)"
              node scripts/decrypt-env.js
            displayName: Desencriptar archivos de entorno

          - powershell: |
              Write-Host "🚀 Ejecutando pruebas Karate..."
              mvn test "-Dtest=test.RunAllTests" "-Dkarate.env=$(ENV)" "-Dsurefire.printSummary=false"
            displayName: Ejecutar Karate Tests
            env:
              TNS_ADMIN: $(Build.SourcesDirectory)\.oracle\network\admin
              JAVA_TOOL_OPTIONS: "-Doracle.jdbc.timezoneAsRegion=false"

          - powershell: |
              Write-Host "📦 Comprimir reportes Karate..."
              $output = "$(Build.ArtifactStagingDirectory)\karate-report.zip"
              $source = "$(Build.SourcesDirectory)\target\karate-reports"
              if (Test-Path $source) {
                Compress-Archive -Path "$source\*" -DestinationPath $output -Force
              } else {
                Write-Host "⚠️ No se encontraron reportes para comprimir"
              }
            displayName: Comprimir reportes Karate
            condition: always()

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "karate-report"
              publishLocation: "Container"
            displayName: Subir reporte Karate ZIP
            condition: always()
